import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "typescript/index.ts",
    runtime: "typescript/runtime.ts",
    "adapters/wasm-adapter": "typescript/adapters/wasm-adapter.ts",
    "ocr/registry": "typescript/ocr/registry.ts",
    "ocr/tesseract-wasm-backend": "typescript/ocr/tesseract-wasm-backend.ts",
    "ocr-worker": "typescript/ocr/ocr-worker.ts",
  },
  format: ["esm"],
  bundle: true,
  dts: false,
  splitting: false,
  sourcemap: true,
  clean: true,
  shims: false,
  platform: "node",
  target: "es2022",
  external: [
    "@kreuzberg/core",
    "tesseract-wasm",
    "../pkg/kreuzberg_wasm.js",
    "./pkg/kreuzberg_wasm.js",
    "./kreuzberg_wasm.js",
    /\.wasm$/,
    /@kreuzberg\/wasm-.*/,
    "./index.js",
    "../index.js",
    "../pdfium.js",
    "./pdfium.js",
    /^node:/,
    "worker_threads",
  ],
});
