// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3c9515252cb2667970473e1656984d163e05e7919e658182a474292055c84cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		setupFiles: ["./setup.ts"],
	},
});
