# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: async
defmodule E2e.AsyncTest do
  use ExUnit.Case, async: false

  describe "async_extract_bytes" do
    test "async_extract_bytes" do
      content = File.read!("../../test_documents/pdf/fake_memo.pdf")
      {:ok, result} = Kreuzberg.extract_bytes_async(content, "application/pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert (is_binary(result.content) && byte_size(result.content) >= 50) || (is_list(result.content) && length(result.content) >= 50) || (is_binary(result.content) == false && is_list(result.content) == false && String.length(result.content) >= 50)
    end
  end

  describe "async_extract_bytes_empty_mime" do
    test "async_extract_bytes_empty_mime" do
      content = File.read!("../../test_documents/text/plain.txt")
      assert {:error, _} = Kreuzberg.extract_bytes_async(content, "", "{}")
    end
  end

  describe "async_extract_bytes_invalid_mime" do
    test "async_extract_bytes_invalid_mime" do
      content = File.read!("../../test_documents/text/plain.txt")
      assert {:error, _} = Kreuzberg.extract_bytes_async(content, "application/x-nonexistent", "{}")
    end
  end
end
