# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: document_extractor_management
defmodule E2e.DocumentExtractorManagementTest do
  use ExUnit.Case, async: false

  describe "document_extractors_clear" do
    test "document_extractors_clear" do
      result = Kreuzberg.clear_document_extractors()
    end
  end

  describe "extractors_list" do
    test "extractors_list" do
      result = Kreuzberg.list_document_extractors()
    end
  end
end
