# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_async_pending
defmodule E2e.EmbedAsyncPendingTest do
  use ExUnit.Case, async: false

  describe "embed_texts_async_empty_input" do
    test "embed_texts_async_empty_input" do
      {:ok, result} = Xberg.embed_texts_async([], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
      assert length(result) == 0
    end
  end

  describe "embed_texts_async_happy" do
    test "embed_texts_async_happy" do
      {:ok, result} = Xberg.embed_texts_async(["First", "Second"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
      assert length(result) >= 2
    end
  end

  describe "embed_texts_async_preset_switch" do
    test "embed_texts_async_preset_switch" do
      {:ok, result} = Xberg.embed_texts_async(["Text"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
