# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:694f1b246852c73b75ff64b8d2a6b78875f1a4c79478935659fc88136f08d52b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: false

  describe "embed_texts_batch" do
    test "embed_texts_batch" do
      {:ok, result} = Kreuzberg.embed_texts(["Hello", "World"], "{}")
    end
  end
end
