# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Xberg.clear_post_processors()
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Xberg.list_post_processors()
    end
  end
end
