# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Kreuzberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Kreuzberg.list_renderers()
    end
  end
end
