# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: summarization
defmodule E2e.SummarizationTest do
  use ExUnit.Case, async: false

  describe "summarization_extractive_smoke" do
    test "summarization_extractive_smoke" do
      {:ok, result} = Kreuzberg.extract_file_sync("../../test_documents/text/book_war_and_peace_1p.txt", config: "{\"summarization\":{\"max_tokens\":80,\"strategy\":\"extractive\"}}")
      assert String.trim(result.mime_type) == "text/plain"
      # skipped: field 'summary.text' not available on result type
      # skipped: field 'summary.strategy' not available on result type
    end
  end
end
