# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: tokenizer_backend_management
defmodule E2e.TokenizerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "tokenizer_backends_clear" do
    test "tokenizer_backends_clear" do
      result = Xberg.clear_tokenizer_backends()
    end
  end

  describe "tokenizer_backends_list" do
    test "tokenizer_backends_list" do
      result = Xberg.list_tokenizer_backends()
    end
  end
end
