# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Kreuzberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Kreuzberg.list_validators()
    end
  end
end
