
respect-gitignore = true
exclude = ["node_modules", "target", "dist", "vendor"]

disable = ["MD012", "MD013", "MD024", "MD030", "MD033", "MD035", "MD036", "MD041", "MD046", "MD051", "MD076"]

[MD024]
siblings_only = true
