// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: document_extractor_management.</summary>
    public class DocumentExtractorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_DocumentExtractorsClear()
        {
            // Clear all document extractors and verify list is empty
            KreuzbergLib.ClearDocumentExtractors();
        }

        [Fact]
        public void Test_ExtractorsList()
        {
            // List all registered document extractors
            var result = KreuzbergLib.ListDocumentExtractors();

        }


    }
}
