// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:26fe7c9733d62addc39a3712d60ac4092700c5b4d5908a58089d3d0a29b9ca78
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: renderer_management.</summary>
    public class RendererManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_RenderersClear()
        {
            // Clear all renderers and verify list is empty
            KreuzbergLib.ClearRenderers();
        }

        [Fact]
        public void Test_RenderersList()
        {
            // List all registered renderers
            var result = KreuzbergLib.ListRenderers();

        }


    }
}
