// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: validator_management.</summary>
    public class ValidatorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ValidatorsClear()
        {
            // Clear all validators and verify list is empty
            KreuzbergLib.ClearValidators();
        }

        [Fact]
        public void Test_ValidatorsList()
        {
            // List all registered validators
            var result = KreuzbergLib.ListValidators();

        }


    }
}
