// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergConverter;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: validator_management.</summary>
    public class ValidatorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ValidatorsClear()
        {
            // Clear all validators and verify list is empty
            KreuzbergConverter.ClearValidators();
        }

        [Fact]
        public void Test_ValidatorsList()
        {
            // List all registered validators
            var result = KreuzbergConverter.ListValidators();

        }


    }
}
