// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.EmbeddingConfig;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: embed_extra. */
public class EmbedExtraTest {

    @Test
    void testEmbedTextsBatch() throws Exception {
        // Batch embed texts
        var config = JsonUtil.fromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig.class);

        var result = Xberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"Hello\"", String.class), JsonUtil.fromJson("\"World\"", String.class)), config);


    }

}
