// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.EmbeddingConfig;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: embed_async_pending. */
public class EmbedAsyncPendingTest {

    @Test
    void testEmbedTextsAsyncEmptyInput() throws Exception {
        // embed_texts_async: empty text list
        var config = JsonUtil.fromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig.class);

        var result = Xberg.embedTextsAsync(java.util.List.of(), config);
        // skipped: field 'embeddings' not available on result type

    }


    @Test
    void testEmbedTextsAsyncHappy() throws Exception {
        // embed_texts_async: basic async embedding
        var config = JsonUtil.fromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig.class);

        var result = Xberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"First\"", String.class), JsonUtil.fromJson("\"Second\"", String.class)), config);
        // skipped: field 'embeddings' not available on result type

    }


    @Test
    void testEmbedTextsAsyncPresetSwitch() throws Exception {
        // embed_texts_async: preset override
        var config = JsonUtil.fromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig.class);

        var result = Xberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"Text\"", String.class)), config);


    }

}
