// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: validator_management. */
public class ValidatorManagementTest {

    @Test
    void testValidatorsClear() throws Exception {
        // Clear all validators and verify list is empty
        Xberg.clearValidators();


    }


    @Test
    void testValidatorsList() throws Exception {
        // List all registered validators
        var result = Xberg.listValidators();


    }

}
