// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c430c8f0405b7a073f1bec71972c9b85ce600a8ec125337f2a7447dfcf206d33
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: document_extractor_management

use kreuzberg::{clear_document_extractors, list_document_extractors};

#[test]
fn test_document_extractors_clear() {
    // Clear all document extractors and verify list is empty
    let _ = clear_document_extractors();
}

#[test]
fn test_extractors_list() {
    // List all registered document extractors
    let _ = list_document_extractors();
}
