// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d54d02cdb3205326ded80317549f83935b0a7c1f83140493e7438876eff482a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: embed_extra

use kreuzberg::embed_texts;

#[test]
fn test_embed_texts_batch() {
    // Batch embed texts
    let texts_json: serde_json::Value = serde_json::from_str(r#"["Hello","World"]"#).unwrap();
    let texts = serde_json::from_value::<Vec<String>>(texts_json).unwrap();
    let config_json: serde_json::Value = serde_json::from_str(r#"{}"#).unwrap();
    let config = serde_json::from_value(config_json).unwrap();
    let _ = embed_texts(texts, &config).expect("should succeed");
}
