// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: registry_operations

use kreuzberg::get_extensions_for_mime;

#[test]
fn test_extensions_docx() {
    // Get file extensions for DOCX MIME type
    let mime_type = r#"application/vnd.openxmlformats-officedocument.wordprocessingml.document"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}

#[test]
fn test_extensions_html() {
    // Get file extensions for HTML MIME type
    let mime_type = r#"text/html"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}

#[test]
fn test_extensions_pdf() {
    // Get file extensions for PDF MIME type
    let mime_type = r#"application/pdf"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}
