// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: registry

use xberg::{list_embedding_backends, list_ocr_backends, list_post_processors, list_renderers, list_validators};

#[test]
fn test_list_embedding_backends() {
    // List embedding backends
    let _ = list_embedding_backends();
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends();
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors();
}

#[test]
fn test_list_renderers() {
    // List renderers
    let _ = list_renderers();
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators();
}
