// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: renderer_management

use kreuzberg::{clear_renderers, list_renderers};

#[test]
fn test_renderers_clear() {
    // Clear all renderers and verify list is empty
    let _ = clear_renderers();
}

#[test]
fn test_renderers_list() {
    // List all registered renderers
    let _ = list_renderers();
}
