// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94844823787c7b9543e9fe1d9873b562b00ebe524891def8ba26c232e52b833e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: validator_management

use kreuzberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let _ = clear_validators();
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
