# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BibtexMetadata do
  @moduledoc "BibTeX bibliography metadata."

  @typedoc "BibTeX bibliography metadata."
  @type t :: %__MODULE__{
  entry_count: non_neg_integer(),
  citation_keys: [String.t()],
  authors: [String.t()],
  year_range: Xberg.YearRange.t() | nil,
  entry_types: map() | nil
  }

  defstruct entry_count: 0,
  citation_keys: [],
  authors: [],
  year_range: nil,
  entry_types: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
