# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  pages: Xberg.PageRange.t(),
  estimated_time_ms: non_neg_integer()
  }

  defstruct index: 0,
  pages: nil,
  estimated_time_ms: 0
end
