# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Citation do
  @moduledoc """
  A structured citation from a citation block.

  Parsed from entries like:
  `[^srcN]: source, locator, excerpt: "text"`
  """

  @typedoc "A structured citation from a citation block."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          source: String.t() | nil,
          locator: String.t() | nil,
          excerpt: String.t() | nil
        }

  defstruct label: nil,
            source: nil,
            locator: nil,
            excerpt: nil
end
