# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Citation do
  @moduledoc """
  A structured citation from a citation block.

  Parsed from entries like:
  `[^srcN]: source, locator, excerpt: "text"`
  """

  @typedoc "A structured citation from a citation block."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          source: String.t() | nil,
          locator: String.t() | nil,
          excerpt: String.t() | nil
        }

  defstruct label: nil,
            source: nil,
            locator: nil,
            excerpt: nil
end
