# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
