# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil
end
