# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
          start_page: non_neg_integer(),
          end_page: non_neg_integer(),
          confidence: float(),
          reason: String.t() | nil
        }

  defstruct start_page: 0,
            end_page: 0,
            confidence: 0.0,
            reason: :start
end
