# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
  start_page: non_neg_integer(),
  end_page: non_neg_integer(),
  confidence: float(),
  reason: String.t() | nil
  }

  defstruct start_page: 0,
  end_page: 0,
  confidence: 0.0,
  reason: :start
end
