# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentMetadata do
  @moduledoc "Metadata about a document for analysis."

  @typedoc "Metadata about a document for analysis."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          size_bytes: non_neg_integer(),
          page_count: non_neg_integer() | nil,
          force_ocr: boolean(),
          user_chunk_config: Xberg.UserChunkConfig.t() | nil,
          chunking_enabled: boolean()
        }

  defstruct mime_type: nil,
            size_bytes: 0,
            page_count: nil,
            force_ocr: false,
            user_chunk_config: nil,
            chunking_enabled: false
end
