# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: map() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
