# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          filename: String.t() | nil,
          mime_type: String.t() | nil,
          size: non_neg_integer() | nil,
          is_image: boolean(),
          data: binary() | nil
        }

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
