# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  filename: String.t() | nil,
  mime_type: String.t() | nil,
  size: non_neg_integer() | nil,
  is_image: boolean(),
  data: binary() | nil
  }

  defstruct name: nil,
  filename: nil,
  mime_type: nil,
  size: nil,
  is_image: false,
  data: nil
end
