# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionConfidence do
  @moduledoc """
  Combined confidence on `[0, 1]`.

  When OCR did not run, the `ocr_aggregate` weight folds into `text_coverage`
  so the weighted sum still totals 1.0.
  """

  @typedoc "Combined confidence on `[0, 1]`."
  @type t :: %__MODULE__{
  text_coverage: float(),
  ocr_aggregate: float() | nil,
  schema_compliance: String.t() | nil,
  combined: float()
  }

  defstruct text_coverage: 0.0,
  ocr_aggregate: nil,
  schema_compliance: :all_valid,
  combined: 0.0
end
