# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionErrorItem do
  @moduledoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."

  @typedoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          code: non_neg_integer(),
          error_type: String.t() | nil,
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct index: 0,
            code: 0,
            error_type: nil,
            source: nil,
            message: nil
end
