# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionConfidence do
  @moduledoc """
  Combined confidence on `[0, 1]`.

  When OCR did not run, the `ocr_aggregate` weight folds into `text_coverage`
  so the weighted sum still totals 1.0.
  """

  @typedoc "Combined confidence on `[0, 1]`."
  @type t :: %__MODULE__{
          text_coverage: float(),
          ocr_aggregate: float() | nil,
          schema_compliance: String.t() | nil,
          combined: float()
        }

  defstruct text_coverage: 0.0,
            ocr_aggregate: nil,
            schema_compliance: :all_valid,
            combined: 0.0
end
