# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteAnchor do
  @moduledoc """
  A footnote anchor reference in markdown text.

  Represents a `[^label]` use-site (not a definition).
  """

  @typedoc "A footnote anchor reference in markdown text."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  offset: non_neg_integer()
  }

  defstruct label: nil,
  offset: 0
end
