# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [map()]
        }

  defstruct label: nil,
            content: []
end
