# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HierarchicalBlock do
  @moduledoc """
  A text block with hierarchy level assignment.

  Represents a block of text with semantic heading information extracted from
  font size clustering and hierarchical analysis.
  """

  @typedoc "A text block with hierarchy level assignment."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  font_size: float(),
  level: String.t() | nil
  }

  defstruct text: nil,
  font_size: 0.0,
  level: nil
end
