# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake
end
