# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
  class_name: String.t() | nil,
  confidence: float(),
  bbox: Xberg.BBox.t()
  }

  defstruct class_name: :caption,
  confidence: 0.0,
  bbox: nil
end
