# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ListType do
  @moduledoc "Type of list detection."

  @typedoc "Type of list detection."
  @type t :: :bullet | :numbered | :lettered | :indented

  @bullet :bullet
  @numbered :numbered
  @lettered :lettered
  @indented :indented

  @doc "Bullet points (-, *, •, etc.)"
  @spec bullet() :: t()
  def bullet, do: @bullet
  @doc "Numbered lists (1., 2., etc.)"
  @spec numbered() :: t()
  def numbered, do: @numbered
  @doc "Lettered lists (a., b., A., B., etc.)"
  @spec lettered() :: t()
  def lettered, do: @lettered
  @doc "Indented items"
  @spec indented() :: t()
  def indented, do: @indented
end
