# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.NerBackendKind do
  @moduledoc "NER backend selector."

  @typedoc "NER backend selector."
  @type t :: :onnx | :llm

  @onnx :onnx
  @llm :llm

  @doc "gline-rs ONNX inference. Requires `ner-onnx` feature. Models download lazily from HuggingFace via `model_download::hf_download`."
  @spec onnx() :: t()
  def onnx, do: @onnx
  @doc "liter-llm zero-shot NER via structured-output prompts. Requires `ner-llm` feature. Useful when domain-specific categories outstrip the ONNX taxonomy."
  @spec llm() :: t()
  def llm, do: @llm
end
