# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrBackendType do
  @moduledoc "OCR backend types."

  @typedoc "OCR backend types."
  @type t :: :tesseract | :paddle_ocr | :candle | :custom

  @tesseract :tesseract
  @paddle_ocr :paddle_ocr
  @candle :candle
  @custom :custom

  @doc "Tesseract OCR (native Rust binding)"
  @spec tesseract() :: t()
  def tesseract, do: @tesseract
  @doc "PaddleOCR (Python-based, via FFI)"
  @spec paddle_ocr() :: t()
  def paddle_ocr, do: @paddle_ocr
  @doc "Candle-based VLM OCR (TrOCR, PaddleOCR-VL)."
  @spec candle() :: t()
  def candle, do: @candle
  @doc "Custom/third-party OCR backend"
  @spec custom() :: t()
  def custom, do: @custom
end
