# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
  prompt_template: String.t() | nil,
  labels: [String.t()],
  multi_label: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct prompt_template: nil,
  labels: [],
  multi_label: false,
  llm: nil
end
