# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageSignals do
  @moduledoc "Per-page signals extracted from PDF content."

  @typedoc "Per-page signals extracted from PDF content."
  @type t :: %__MODULE__{
  page_number: non_neg_integer(),
  text_excerpt: String.t() | nil,
  starts_with_letterhead_like: boolean(),
  has_page_number_one_marker: boolean(),
  has_signature_block: boolean(),
  layout_text_density: float()
  }

  defstruct page_number: 0,
  text_excerpt: nil,
  starts_with_letterhead_like: false,
  has_page_number_one_marker: false,
  has_signature_block: false,
  layout_text_density: 0.0
end
