# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer(),
  category: String.t() | nil,
  text: String.t() | nil
  }

  defstruct start: 0,
  end: 0,
  category: :email,
  text: nil
end
