# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct source: nil,
            message: nil
end
