# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: Xberg.QrBoundingBox.t() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
