# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionTerm do
  @moduledoc """
  One user-supplied literal term to redact.

  Matched as a regex-escaped substring (so callers do not need to escape
  metacharacters themselves). Case-insensitive by default — set
  [`Self::case_sensitive`] to `true` for exact byte-match semantics.
  """

  @typedoc "One user-supplied literal term to redact."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  value: String.t() | nil,
  case_sensitive: boolean()
  }

  defstruct label: nil,
  value: nil,
  case_sensitive: false
end
