# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionPattern do
  @moduledoc """
  One user-supplied regex pattern to redact.

  The pattern is compiled with the Rust `regex` crate (no look-around). Case
  sensitivity is encoded in the pattern via the `(?i)` inline flag when
  [`Self::case_sensitive`] is `false`.
  """

  @typedoc "One user-supplied regex pattern to redact."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  pattern: String.t() | nil,
  case_sensitive: boolean()
  }

  defstruct label: nil,
  pattern: nil,
  case_sensitive: false
end
