# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Xberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
          extension: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct extension: nil,
            mime_type: nil
end
