# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SvgOptions do
  @moduledoc """
  SVG-specific configuration for the image-encode pipeline.

  Applies when the source image is SVG or when the output format is set to
  [`ImageOutputFormat::Svg`].  Available when the `svg` feature is active.

  Used via [`ImageExtractionConfig::svg`].
  """

  @typedoc "SVG-specific configuration for the image-encode pipeline."
  @type t :: %__MODULE__{
  sanitize: boolean(),
  render_dpi: float()
  }

  defstruct sanitize: true,
  render_dpi: 96

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
