# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SvgOptions do
  @moduledoc """
  SVG-specific configuration for the image-encode pipeline.

  Applies when the source image is SVG or when the output format is set to
  [`ImageOutputFormat::Svg`].  Available when the `svg` feature is active.

  Used via [`ImageExtractionConfig::svg`].
  """

  @typedoc "SVG-specific configuration for the image-encode pipeline."
  @type t :: %__MODULE__{
          sanitize: boolean(),
          render_dpi: float()
        }

  defstruct sanitize: true,
            render_dpi: 96

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
