# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [map()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
