# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          preserve_important_words: boolean()
        }

  defstruct mode: nil,
            preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
