<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: detection. */
final class DetectionTest extends TestCase
{

    /** Detect HTML MIME from bytes */
    public function test_detect_mime_bytes_html(): void
    {
        $contentBytes = file_get_contents("html/html.html");
        if ($contentBytes === false) { $this->fail("failed to read fixture: html/html.html"); }
        $this->expectNotToPerformAssertions();
        $result = Xberg::detectMimeTypeFromBytes($contentBytes);


    }


    /** Detect PDF MIME type from bytes */
    public function test_detect_mime_bytes_pdf(): void
    {
        $contentBytes = file_get_contents("pdf/fake_memo.pdf");
        if ($contentBytes === false) { $this->fail("failed to read fixture: pdf/fake_memo.pdf"); }
        $this->expectNotToPerformAssertions();
        $result = Xberg::detectMimeTypeFromBytes($contentBytes);


    }


    /** Detect PNG MIME type from bytes */
    public function test_detect_mime_bytes_png(): void
    {
        $contentBytes = file_get_contents("images/test_hello_world.png");
        if ($contentBytes === false) { $this->fail("failed to read fixture: images/test_hello_world.png"); }
        $this->expectNotToPerformAssertions();
        $result = Xberg::detectMimeTypeFromBytes($contentBytes);


    }


    /** get_extensions unknown MIME */
    public function test_get_extensions_unknown_mime(): void
    {
        $this->expectException(\Exception::class);        Xberg::getExtensionsForMime("application/x-totally-unknown");
    }

}
