<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\EmbeddingConfig;

/** E2e tests for category: embed_extra. */
final class EmbedExtraTest extends TestCase
{

    /** Batch embed texts */
    public function test_embed_texts_batch(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Hello", "World"], $config);


    }

}
