<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\ExtractionConfig;
use Xberg\Xberg;

/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{
    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearRenderers();
    }

    /** List all registered renderers */
    public function test_renderers_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listRenderers();
    }
}
