<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: tokenizer_backend_management. */
final class TokenizerBackendManagementTest extends TestCase
{

    /** Clear all tokenizer backends and verify list is empty */
    public function test_tokenizer_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearTokenizerBackends();


    }


    /** List all registered tokenizer backends */
    public function test_tokenizer_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listTokenizerBackends();


    }

}
