<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1d43bc71b7b704c31fda0457c19e28b21bdf9005587da81cd8aefa9c35351b6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();


    }

}
