// Generated by alef. Do not edit by hand.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Options controlling how two `ExtractionResult` values are compared. */
data class DiffOptions(
    /** Include metadata changes in the diff. Default: `true`. */
    val includeMetadata: Boolean = true,
    /** Include embedded-children changes in the diff. Default: `true`. */
    val includeEmbedded: Boolean = true,
    /**
     * Truncate content to this many characters before diffing.
     *
     * Useful for very large documents where only the first N characters matter.
     * `null` means no truncation.
     */
    val maxContentChars: Long? = null,
)
