// Generated by alef. Do not edit by hand.
// alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de

package dev.kreuzberg

class KreuzbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
