// Generated by alef. Do not edit by hand.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/**
 * Confidence scores for an OCR element.
 *
 * Separates detection confidence (how confident that text exists at this location)
 * from recognition confidence (how confident about the actual text content).
 */
data class OcrConfidence(
    /**
     * Detection confidence: how confident the OCR engine is that text exists here.
     *
     * PaddleOCR provides this as `box_score`, Tesseract doesn't have a direct equivalent.
     * Range: 0.0 to 1.0 (or None if not available).
     */
    val detection: Double? = null,
    /**
     * Recognition confidence: how confident about the text content.
     *
     * Range: 0.0 to 1.0.
     */
    val recognition: Double = 0.0,
)
