// Generated by alef. Do not edit by hand.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/**
 * One user-supplied regex pattern to redact.
 *
 * The pattern is compiled with the Rust `regex` crate (no look-around). Case
 * sensitivity is encoded in the pattern via the `(?i)` inline flag when
 * `Self.case_sensitive` is `false`.
 */
data class RedactionPattern(
    /** Custom category label surfaced in `RedactionFinding.category`. */
    val label: String,
    /** Regex pattern (Rust `regex` crate dialect — no look-around). */
    val pattern: String,
    /** When `true`, match case-sensitively; otherwise prepend `(?i)` to the regex. */
    val caseSensitive: Boolean,
)
