// Generated by alef. Do not edit by hand.
// alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b

package dev.kreuzberg

object ValidatorBridge {
    private val registered = mutableMapOf<String, IValidator>()

    fun register(impl: IValidator): Unit {
        val name = impl.name()
        registered[name] = impl
        KreuzbergBridge.nativeRegisterValidator(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        KreuzbergBridge.nativeUnregisterValidator(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        KreuzbergBridge.nativeClearValidators()
    }

    fun getAll(): Map<String, IValidator> = registered.toMap()
}
