// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8df2a6db7f3da5a4971d032be6bdeadc9ba41d8a78baeef03c7cf722873a9af6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg

/// E2e tests for category: detection.
final class DetectionTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testDetectMimeBytesHtml() throws {
        // Detect HTML MIME from bytes
        let contentData = try Data(contentsOf: URL(fileURLWithPath: "html/html.html"))
        let contentVec = RustBridge.RustVec<UInt8>()
        for _byte in contentData { contentVec.push(value: _byte) }
        let result = try Kreuzberg.detectMimeTypeFromBytes(contentVec)
    }

    func testDetectMimeBytesPdf() throws {
        // Detect PDF MIME type from bytes
        let contentData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
        let contentVec = RustBridge.RustVec<UInt8>()
        for _byte in contentData { contentVec.push(value: _byte) }
        let result = try Kreuzberg.detectMimeTypeFromBytes(contentVec)
    }

    func testDetectMimeBytesPng() throws {
        // Detect PNG MIME type from bytes
        let contentData = try Data(contentsOf: URL(fileURLWithPath: "images/test_hello_world.png"))
        let contentVec = RustBridge.RustVec<UInt8>()
        for _byte in contentData { contentVec.push(value: _byte) }
        let result = try Kreuzberg.detectMimeTypeFromBytes(contentVec)
    }

    func testGetExtensionsUnknownMime() throws {
        // get_extensions unknown MIME
        do {
            _ = try Kreuzberg.getExtensionsForMime(mimeType: "application/x-totally-unknown")
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

}
