// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        let result = try Kreuzberg.clearEmbeddingBackends()
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

}
