// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7b397069197024c6a285dc933e0f43539044d9cb7d7eea378bd37c61732bf3d7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg

/// E2e tests for category: embed_async_pending.
final class EmbedAsyncPendingTests: XCTestCase {
    func testEmbedTextsAsyncEmptyInput() async throws {
        // embed_texts_async: empty text list
        let configObj = try extractionConfigFromJson("{}")
        let result = try await Kreuzberg.embedTextsAsync(texts: [], config: configObj)
        XCTAssertEqual(result.embeddings().count, 0)
    }

    func testEmbedTextsAsyncHappy() async throws {
        // embed_texts_async: basic async embedding
        let configObj = try extractionConfigFromJson("{}")
        let result = try await Kreuzberg.embedTextsAsync(texts: ["First", "Second"], config: configObj)
        XCTAssertGreaterThanOrEqual(result.embeddings().count, 2)
    }

    func testEmbedTextsAsyncPresetSwitch() async throws {
        // embed_texts_async: preset override
        let configObj = try extractionConfigFromJson("{\"model\":{\"name\":\"default\",\"type\":\"preset\"}}")
        let result = try await Kreuzberg.embedTextsAsync(texts: ["Text"], config: configObj)
    }

}
