// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a3c9515252cb2667970473e1656984d163e05e7919e658182a474292055c84cc
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
