// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up unchanged.
/// </summary>
public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
