// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
