// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
