// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
