// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
