// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
