// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
