// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Classification of a detected layout region that warrants VLM extraction.
///
/// Each variant maps to a specific prompt optimised for that content type.
/// The mapping is intentionally narrow — only region kinds for which VLM
/// extraction provides a clear quality benefit over classical suppression.
/// </summary>
[JsonConverter(typeof(RegionKindJsonConverter))]
public enum RegionKind
{
    /// <summary>
    /// A figure, diagram, chart, or image region.
    ///
    /// VLM prompt: describe the diagram / chart, including axis labels,
    /// legend entries, and any embedded text.
    /// </summary>
    [JsonPropertyName("figure")]
    Figure,
    /// <summary>
    /// A densely formatted or complex table that classical extraction garbles.
    ///
    /// VLM prompt: extract the table as GitHub-Flavoured Markdown.
    /// </summary>
    [JsonPropertyName("densetable")]
    DenseTable,
    /// <summary>
    /// A region whose layout the classical pipeline cannot handle (multi-column
    /// insets, heavily annotated forms, mixed text+diagram).
    ///
    /// VLM prompt: extract all text and structure as markdown, preserving
    /// reading order.
    /// </summary>
    [JsonPropertyName("complexlayout")]
    ComplexLayout,
}


/// <summary>
/// Custom JSON converter for <see cref="RegionKind"/> that respects explicit variant names.
/// </summary>
internal sealed class RegionKindJsonConverter : JsonConverter<RegionKind>
{
    public override RegionKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "figure" => RegionKind.Figure,
            "densetable" => RegionKind.DenseTable,
            "complexlayout" => RegionKind.ComplexLayout,
            _ => throw new JsonException($"Unknown RegionKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, RegionKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            RegionKind.Figure => "figure",
            RegionKind.DenseTable => "densetable",
            RegionKind.ComplexLayout => "complexlayout",
            _ => throw new JsonException($"Unknown RegionKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
