// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
