// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : KreuzbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
