// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The document's MIME type is not supported by any registered extractor.
/// </summary>
public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
