// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The document's MIME type is not supported by any registered extractor.
/// </summary>
public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
