// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: embeddings.
final class EmbeddingsTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testEmbedTextsDifferentPreset() async throws {
        // embed_texts: multilingual preset
        let configObj = try Xberg.embeddingConfigFromJson("{\"model\":{\"name\":\"multilingual\",\"type\":\"preset\"}}")
        let result = try await Xberg.embedTextsAsync(texts: ["Hello world", "Test"], config: configObj)
        // skipped: field 'embeddings' not available on result type
    }

    func testGetEmbeddingPresetKnown() throws {
        // get_embedding_preset: known preset
        let result = try Xberg.getEmbeddingPreset(name: "balanced")
    }

    func testGetEmbeddingPresetNominal() throws {
        // get_embedding_preset: nominal case
        let result = try Xberg.getEmbeddingPreset(name: "balanced")
    }

    func testGetEmbeddingPresetUnknown() throws {
        // get_embedding_preset: unknown preset fails
        let result = try Xberg.getEmbeddingPreset(name: "nonexistent-xyz")
        XCTAssertNil(result, "expected nil value")
    }

    func testListEmbeddingPresetsSanity() throws {
        // list_embedding_presets: returns at least one
        let result = try Xberg.listEmbeddingPresets()
        XCTAssertFalse(result.isEmpty, "expected non-empty value")
    }

}
