// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.xberg.ExtractionConfig

/** E2e tests for category: async. */
class AsyncTest {

    companion object {
        init {
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testAsyncExtractBytes() = runBlocking {
        // Async extract_bytes call on PDF document
        val result = Xberg.extractBytes(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/fake_memo.pdf")), "application/pdf", ExtractionConfig())
        assertEquals("application/pdf", result.mimeType.trim())
        assertTrue(result.content.length >= 50, "expected length >= 50")
    }

    @Test
    fun testAsyncExtractBytesEmptyMime() = runBlocking {
        // extract_bytes empty MIME async
        assertFailsWith<Exception> {
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extractBytes(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("text/plain.txt")), "", config)
        }
        Unit
    }

    @Test
    fun testAsyncExtractBytesInvalidMime() = runBlocking {
        // extract_bytes unsupported MIME async
        assertFailsWith<Exception> {
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extractBytes(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("text/plain.txt")), "application/x-nonexistent", config)
        }
        Unit
    }

}
