// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg

/** E2e tests for category: detection. */
class DetectionTest {

    companion object {
        init {
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testDetectMimeBytesHtml() = runBlocking {
        // Detect HTML MIME from bytes
        val result = Xberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("html/html.html")))
    }

    @Test
    fun testDetectMimeBytesPdf() = runBlocking {
        // Detect PDF MIME type from bytes
        val result = Xberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/fake_memo.pdf")))
    }

    @Test
    fun testDetectMimeBytesPng() = runBlocking {
        // Detect PNG MIME type from bytes
        val result = Xberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("images/test_hello_world.png")))
    }

    @Test
    fun testGetExtensionsUnknownMime() = runBlocking {
        // get_extensions unknown MIME
        assertFailsWith<Exception> {
            Xberg.getExtensionsForMime("application/x-totally-unknown")
        }
        Unit
    }

}
