// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.RendererBridge
import io.xberg.IRenderer
import io.xberg.*

/** E2e tests for category: renderer_management. */
class RendererManagementTest {

    companion object {
        init {
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testRenderersClear() = runBlocking {
        // Clear all renderers and verify list is empty
        val result = RendererBridge.clearAll()
    }

    @Test
    fun testRenderersList() = runBlocking {
        // List all registered renderers
        val result = Xberg.listRenderers()
    }

}
