/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RendererBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  render?(doc: string): string;
}

export class RendererAdapter {
  constructor(private bridge: RendererBridge) {}

  async render(doc: string): Promise<string> {
    try {
      const result = await this.bridge.render(doc);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
