/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RendererBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  render?(doc: string): string;
}

export class RendererAdapter {
  constructor(private bridge: RendererBridge) {}

  async render(doc: string): Promise<string> {
    try {
      const result = await this.bridge.render(doc);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
