# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba2bf524a11e4984b43c63b159f9691f23935a4c73f5ff11fc2d0cd506ce0dd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: renderer_management

test_that("renderers_clear: Clear all renderers and verify list is empty", {
  invisible(clear_renderers())
  expect_true(TRUE)
})

test_that("renderers_list: List all registered renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})
