# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba2bf524a11e4984b43c63b159f9691f23935a4c73f5ff11fc2d0cd506ce0dd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  invisible(clear_document_extractors())
  expect_true(TRUE)
})

test_that("extractors_list: List all registered document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})
