# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1193e98539221caa392b359c7ffe6d5f810f25b1eb7223829f49e7fb25f9111f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: renderer_management

test_that("renderers_clear: Clear all renderers and verify list is empty", {
  invisible(clear_renderers())
  expect_true(TRUE)
})

test_that("renderers_list: List all registered renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})
