# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b7840d763a3758ede88e25d02264af139dd6f63ddf196b805ac1dde70a239822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embedding_backend_management

test_that("embedding_backends_clear: Clear all embedding backends and verify list is empty", {
  invisible(clear_embedding_backends())
  expect_true(TRUE)
})

test_that("embedding_backends_list: List all registered embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})
