// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException
{
    public IdMismatchException(string message) : base(message) { }

    public IdMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
