// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up unchanged.
/// </summary>
public class IoException : XbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
