// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException
{
    public SchemaValidationException(string message) : base(message) { }

    public SchemaValidationException(string message, Exception innerException) : base(message, innerException) { }
}
