// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
