// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
