// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
