// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : XbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
