// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception
{
    public int Code { get; }

    public XbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public XbergException(string message) : base(message)
    {
        Code = 0;
    }

    public XbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
