// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: document_extractor_management

test "document_extractors_clear" {
    // Clear all document extractors and verify list is empty
    suppress_abort();
    _ = try xberg.clear_document_extractors();
}

test "extractors_list" {
    // List all registered document extractors
    suppress_abort();
    _ = try xberg.list_document_extractors();
}
