// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:83d97f88f9dc6b333adda12aface703f9f799d0d509ee723fb236a663c691282
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: embedding_backend_management

test "embedding_backends_clear" {
    // Clear all embedding backends and verify list is empty
    _ = try kreuzberg.clear_embedding_backends();
}

test "embedding_backends_list" {
    // List all registered embedding backends
    _ = try kreuzberg.list_embedding_backends();
}
