<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Xberg;

/**
 * liter-llm-backed NER backend.
 */
final class LlmBackend
{
    /**
     * @param array<EntityCategory> $categories
     * @return array<Entity>
     */
    public function detect(string $text, array $categories): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * @param array<EntityCategory> $categories
     * @param array<string> $custom_labels
     * @return array<Entity>
     */
    public function detectWithCustom(string $text, array $categories, array $custom_labels): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Create a new LLM-backed NER backend with the given LLM configuration.
     */
    public static function new(LlmConfig $config): LlmBackend
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
