<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Xberg;

/**
 * Compiled meta-schema validator over `preset.schema.json`.
 */
final class MetaSchema
{
    /**
     * Validate `raw` against the meta-schema and deserialize into a `Preset`,
     */
    public function parsePreset(string $path, string $raw): Preset
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Compile the given JSON text as a Draft 2020-12 meta-schema.
     */
    public static function compile(string $meta_schema_json): MetaSchema
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
