// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44e75d2b8996c9d5cce1ccb2f2287880cf4b2c8b5101e514b917928468f75b8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.EmbeddingConfig;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: embed_extra. */
class EmbedExtraTest {

    @Test
    void testEmbedTextsBatch() throws Exception {
        // Batch embed texts
        var config = JsonUtil.fromJson("{}", EmbeddingConfig.class);

        var result = Kreuzberg.embedTexts(java.util.Arrays.asList(JsonUtil.fromJson("\"Hello\"", String.class), JsonUtil.fromJson("\"World\"", String.class)), config);

    }

}
