// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0b28222f1ae93111e3fd5323263e91322bf22f847de748d0fca79e3ddc496822
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: registry_operations. */
class RegistryOperationsTest {

    @Test
    void testExtensionsDocx() throws Exception {
        // Get file extensions for DOCX MIME type
        var result = Kreuzberg.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");

    }


    @Test
    void testExtensionsHtml() throws Exception {
        // Get file extensions for HTML MIME type
        var result = Kreuzberg.getExtensionsForMime("text/html");

    }


    @Test
    void testExtensionsPdf() throws Exception {
        // Get file extensions for PDF MIME type
        var result = Kreuzberg.getExtensionsForMime("application/pdf");
assertTrue(result.contains("pdf"), "expected to contain: " + "pdf");
    }

}
