// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: validator_management. */
public class ValidatorManagementTest {

    @Test
    void testValidatorsClear() throws Exception {
        // Clear all validators and verify list is empty
        Kreuzberg.clearValidators();


    }


    @Test
    void testValidatorsList() throws Exception {
        // List all registered validators
        var result = Kreuzberg.listValidators();


    }

}
