# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
