// DO NOT EDIT - auto-generated by alef
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
package dev.kreuzberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
