// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * Captioning enrichment knob: which LLM to use for image captions.
 *
 * The enrichment stage calls {@code caption_image} for every
 * image in {@code ExtractionResult.images} that has non-empty {@code data}. Images with
 * empty byte data (e.g. reference-only images populated via {@code source_path}) are
 * skipped rather than forwarded to the VLM.
 */
@SuppressWarnings("PMD")
public record CaptioningEnrichmentConfig(
    LlmConfig config,
    @Nullable @JsonProperty("custom_prompt") String customPrompt
) {
}
