// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * MIME type detection response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DetectResponse.Builder.class)
@SuppressWarnings("PMD")
public record DetectResponse(
    @JsonProperty("mime_type") String mimeType,
    @Nullable @JsonProperty("filename") String filename
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("mime_type")
private String mimeType = "";
private String filename = null;

        /** Sets the mimeType field. */
        @JsonProperty("mime_type")
        public Builder withMimeType(final String value) {
            this.mimeType = value;
            return this;
        }

        /** Sets the filename field. */
        @JsonProperty("filename")
        public Builder withFilename(final @Nullable String value) {
            this.filename = value;
            return this;
        }

        /** Builds the DetectResponse instance. */
        public DetectResponse build() {
            return new DetectResponse(
                mimeType,
                filename
            );
        }
    }
    // CPD-ON
}
