// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Summary of an extracted document.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocumentSummary.Builder.class)
@SuppressWarnings("PMD")
public record DocumentSummary(
    @JsonProperty("text") String text,
    @JsonProperty("strategy") SummaryStrategy strategy,
    @Nullable @JsonProperty("token_count") Integer tokenCount
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String text = "";
private SummaryStrategy strategy = null;
        @JsonProperty("token_count")
private Integer tokenCount = null;

        /** Sets the text field. */
        @JsonProperty("text")
        public Builder withText(final String value) {
            this.text = value;
            return this;
        }

        /** Sets the strategy field. */
        @JsonProperty("strategy")
        public Builder withStrategy(final SummaryStrategy value) {
            this.strategy = value;
            return this;
        }

        /** Sets the tokenCount field. */
        @JsonProperty("token_count")
        public Builder withTokenCount(final @Nullable int value) {
            this.tokenCount = value;
            return this;
        }

        /** Builds the DocumentSummary instance. */
        public DocumentSummary build() {
            return new DocumentSummary(
                text,
                strategy,
                tokenCount
            );
        }
    }
    // CPD-ON
}
