// DO NOT EDIT - auto-generated by alef
// alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
package dev.kreuzberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
