// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Layout detection configuration.
 *
 * Controls layout detection behavior in the extraction pipeline.
 * When set on ExtractionConfig(super.ExtractionConfig), layout detection
 * is enabled for PDF extraction.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LayoutDetectionConfig.Builder.class)
public record LayoutDetectionConfig(
    @Nullable @JsonProperty("confidence_threshold") Float confidenceThreshold,
    @Nullable @JsonProperty("apply_heuristics") Boolean applyHeuristics,
    @Nullable @JsonProperty("table_model") TableModel tableModel,
    @Nullable @JsonProperty("acceleration") AccelerationConfig acceleration
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }
    public LayoutDetectionConfig{
        if (applyHeuristics == null) { applyHeuristics = true; }
    }

    // CPD-OFF
    /** Jackson builder for LayoutDetectionConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("confidence_threshold")
        @Nullable private Float confidenceThreshold;
        @JsonProperty("apply_heuristics")
        @Nullable private Boolean applyHeuristics;
        @JsonProperty("table_model")
        @Nullable private TableModel tableModel = TableModel.Tatr;
        @Nullable private AccelerationConfig acceleration;

        /** Sets the confidenceThreshold field. */
        @JsonProperty("confidence_threshold")
        public Builder withConfidenceThreshold(final @Nullable Float value) {
            this.confidenceThreshold = value;
            return this;
        }

        /** Sets the applyHeuristics field. */
        @JsonProperty("apply_heuristics")
        public Builder withApplyHeuristics(final @Nullable Boolean value) {
            this.applyHeuristics = value;
            return this;
        }

        /** Sets the tableModel field. */
        @JsonProperty("table_model")
        public Builder withTableModel(final @Nullable TableModel value) {
            this.tableModel = value;
            return this;
        }

        /** Sets the acceleration field. */
        @JsonProperty("acceleration")
        public Builder withAcceleration(final @Nullable AccelerationConfig value) {
            this.acceleration = value;
            return this;
        }

        /** Constructs a LayoutDetectionConfig instance from the builder's current state. */
        public LayoutDetectionConfig build() {
            return new LayoutDetectionConfig(
                confidenceThreshold,
                applyHeuristics,
                tableModel,
                acceleration
            );
        }
    }
    // CPD-ON
}
