// DO NOT EDIT - auto-generated by alef
// alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
package dev.kreuzberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
