// DO NOT EDIT - auto-generated by alef
// alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
package dev.kreuzberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
