// DO NOT EDIT - auto-generated by alef
// alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
package dev.kreuzberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParsingException with the given message. */
  public ParsingException(final String message) {
    super(message);
  }

  /** Creates a new ParsingException with the given message and cause. */
  public ParsingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
