// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * One QR code decoded from an extracted image.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QrCode.Builder.class)
@SuppressWarnings("PMD")
public record QrCode(
    @JsonProperty("payload") String payload,
    @Nullable @JsonProperty("confidence") Float confidence,
    @Nullable @JsonProperty("bbox") QrBoundingBox bbox
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String payload = "";
private Float confidence = null;
private QrBoundingBox bbox = null;

        /** Sets the payload field. */
        @JsonProperty("payload")
        public Builder withPayload(final String value) {
            this.payload = value;
            return this;
        }

        /** Sets the confidence field. */
        @JsonProperty("confidence")
        public Builder withConfidence(final @Nullable float value) {
            this.confidence = value;
            return this;
        }

        /** Sets the bbox field. */
        @JsonProperty("bbox")
        public Builder withBbox(final @Nullable QrBoundingBox value) {
            this.bbox = value;
            return this;
        }

        /** Builds the QrCode instance. */
        public QrCode build() {
            return new QrCode(
                payload,
                confidence,
                bbox
            );
        }
    }
    // CPD-ON
}
