// DO NOT EDIT - auto-generated by alef
// alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
package dev.kreuzberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends KreuzbergErrorException {
    /** Creates a new RerankingException with the given message. */
    public RerankingException(final String message) {
        super(message);
    }

    /** Creates a new RerankingException with the given message and cause. */
    public RerankingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
