// DO NOT EDIT - auto-generated by alef
// alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
