// DO NOT EDIT - auto-generated by alef
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
package dev.kreuzberg;

/**
 * JSON or MessagePack serialization/deserialization failed.
 */
public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
