// DO NOT EDIT - auto-generated by alef
// alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
