// DO NOT EDIT - auto-generated by alef
// alef:hash:a3c9515252cb2667970473e1656984d163e05e7919e658182a474292055c84cc
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
