# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "kreuzberg/version"
require_relative "kreuzberg/native"

# Top-level namespace for the Kreuzberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "kreuzberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Kreuzberg
  # Re-export all types and functions from native extension
end
