# Generated by alef. Do not edit by hand.
# alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
