# Generated by alef. Do not edit by hand.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
