// Generated by alef. Do not edit by hand.
// alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "kreuzberg-android"
