// Generated by alef. Do not edit by hand.
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26

package io.xberg

object DocumentExtractorBridge {
    private val registered = mutableMapOf<String, IDocumentExtractor>()

    fun register(impl: IDocumentExtractor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterDocumentExtractor(DocumentExtractorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterDocumentExtractor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearDocumentExtractors()
    }

    fun getAll(): Map<String, IDocumentExtractor> = registered.toMap()
}
