// Generated by alef. Do not edit by hand.
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26

package io.xberg

import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import kotlinx.coroutines.runBlocking
/**
 * JSON dispatch wrapper for [IEmbeddingBackend] implementations, called from the
 * native trait bridge. Decodes each trait call's arguments, invokes the typed
 * implementation (bridging suspend methods via runBlocking), and encodes the
 * result as {"ok": ...} on success or {"err": "..."} on failure.
 */
internal class EmbeddingBackendJniDispatcher(private val impl: IEmbeddingBackend) {
    private val mapper = jacksonObjectMapper()

    /** JSON array of the Rust-side names of the methods this host provides. */
    fun implementedMethods(): String =
    mapper.writeValueAsString(
        listOf(
            "dimensions",
            "embed",
            "name",
            "version",
            "initialize",
            "shutdown",
        ),
    )

    @Suppress("UNUSED_PARAMETER", "CyclomaticComplexMethod")
    fun dispatch(method: String, argsJson: String): String =
    try {
        val args = mapper.readTree(argsJson)
        val result: Any? =
        when (method) {
            "dimensions" -> impl.dimensions()
            "embed" -> runBlocking { impl.embed(mapper.convertValue(args.get("texts"), object : com.fasterxml.jackson.core.type.TypeReference<List<String>>() {})) }
            "name" -> impl.name()
            "version" -> impl.version()
            "initialize" -> {
                impl.initialize()
                null
            }
            "shutdown" -> {
                impl.shutdown()
                null
            }
            else -> throw IllegalArgumentException("unknown trait method: $method")
        }
        mapper.writeValueAsString(mapOf("ok" to result))
    } catch (t: Throwable) {
        mapper.writeValueAsString(mapOf("err" to (t.message ?: t.toString())))
    }
}
