// Generated by alef. Do not edit by hand.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394

package io.xberg

object OcrBackendBridge {
    private val registered = mutableMapOf<String, IOcrBackend>()

    fun register(impl: IOcrBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterOcrBackend(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterOcrBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearOcrBackends()
    }

    fun getAll(): Map<String, IOcrBackend> = registered.toMap()
}
