// Generated by alef. Do not edit by hand.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db

package io.xberg

object PostProcessorBridge {
    private val registered = mutableMapOf<String, IPostProcessor>()

    fun register(impl: IPostProcessor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterPostProcessor(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterPostProcessor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearPostProcessors()
    }

    fun getAll(): Map<String, IPostProcessor> = registered.toMap()
}
