// Generated by alef. Do not edit by hand.
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938

package io.xberg

object RerankerBackendBridge {
    private val registered = mutableMapOf<String, IRerankerBackend>()

    fun register(impl: IRerankerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterRerankerBackend(RerankerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterRerankerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearRerankerBackends()
    }

    fun getAll(): Map<String, IRerankerBackend> = registered.toMap()
}
