// Generated by alef. Do not edit by hand.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394

package io.xberg

class XbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
