// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bddcd65d94177856eec9df7bd0c75fa1ca20117a8fbf32cff6e480e6efc361e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * JATS (Journal Article Tag Suite) metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record JatsMetadata(
    @Nullable String copyright,
    @Nullable String license,
    @JsonProperty("history_dates") Map<String, String> historyDates,
    @JsonProperty("contributor_roles") List<ContributorRole> contributorRoles
) {
}
