// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:74a62c9bc478bc8de677f50ce878de9fe2eeb62297bc4b75041b84f2d2e5bce1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single layout detection result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LayoutDetection(
    @JsonProperty("class_name") LayoutClass className,
    float confidence,
    BBox bbox
) {
}
