// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a9226cdc0fdf55fc9b0c2f276b3c9a494e8acb286924d728bd60718abb19689
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * OCR processing metadata.
 *
 * Captures information about OCR processing configuration and results.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrMetadata(
    /**
     * OCR language code(s) used
     */
    String language,
    /**
     * Tesseract Page Segmentation Mode (PSM)
     */
    int psm,
    /**
     * Output format (e.g., "text", "hocr")
     */
    @JsonProperty("output_format") String outputFormat,
    /**
     * Number of tables detected
     */
    @JsonProperty("table_count") int tableCount,
    @Nullable @JsonProperty("table_rows") Integer tableRows,
    @Nullable @JsonProperty("table_cols") Integer tableCols
) {
}
