// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea90df4f2bfa5079ef6d1970b4f0ad6fc7b792a5d7cc1ce06edc2d57aa2d4fcf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box for an OCR-detected table in pixel coordinates.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrTableBoundingBox(int left, int top, int right, int bottom) {
}
