// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7e88219ad34f1f3f1da5b3884196b216b5c999435821a856d464ccbce516bab8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredDataResult(
    String content,
    String format,
    Map<String, String> metadata,
    @JsonProperty("text_fields") List<String> textFields
) {
}
