# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:878b6dc22474c70a0bbe01eb6c0f1f26beaa103f33d48cafac0925a61630d0b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchFileItem do  @moduledoc "Batch item for file extraction."
  defstruct path: "",
            config: nil
end
