# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchFileItem do
  @moduledoc """
  Batch item for file extraction.

  Used with `batch_extract_files` and `batch_extract_files_sync`
  to represent a single file in a batch extraction job.
  """

  @typedoc "Batch item for file extraction."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          config: map() | nil
        }

  defstruct path: nil,
            config: nil
end
