# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BoundingBox do
  @moduledoc "Bounding box coordinates for element positioning."

  @typedoc "Bounding box coordinates for element positioning."
  @type t :: %__MODULE__{
          x0: float(),
          y0: float(),
          x1: float(),
          y1: float()
        }

  defstruct x0: 0.0,
            y0: 0.0,
            x1: 0.0,
            y1: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
