# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CacheStats do
  @moduledoc "Aggregate statistics for a kreuzberg cache directory."

  @typedoc "Aggregate statistics for a kreuzberg cache directory."
  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float(),
          available_space_mb: float(),
          oldest_file_age_days: float(),
          newest_file_age_days: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0,
            available_space_mb: 0.0,
            oldest_file_age_days: 0.0,
            newest_file_age_days: 0.0
end
