# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: map(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: 0
end
