# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14853cc17c4763ed292da0c0e3acc3fae88d2b9d757023ee1a281da3ca502623
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkingConfig do  @moduledoc "Chunking configuration."
  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil
end
