# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  @typedoc "Citation file metadata (RIS, PubMed, EndNote)."
  @type t :: %__MODULE__{
          citation_count: non_neg_integer(),
          format: String.t() | nil,
          authors: [String.t()],
          year_range: map() | nil,
          dois: [String.t()],
          keywords: [String.t()]
        }

  defstruct citation_count: 0,
            format: nil,
            authors: [],
            year_range: nil,
            dois: [],
            keywords: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
