# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
