# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DiffLine do
  @moduledoc """
  A single line in a unified-diff hunk.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single line in a unified-diff hunk."
  @type t :: term()

  @typedoc "Unchanged context line."
  @type context :: %{type: :context, value: String.t()}
  @typedoc "Line added in the \"after\" version."
  @type added :: %{type: :added, value: String.t()}
  @typedoc "Line removed from the \"before\" version."
  @type removed :: %{type: :removed, value: String.t()}
end
