# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DiffOptions do
  @moduledoc "Options controlling how two `ExtractionResult` values are compared."

  @typedoc "Options controlling how two `ExtractionResult` values are compared."
  @type t :: %__MODULE__{
          include_metadata: boolean(),
          include_embedded: boolean(),
          max_content_chars: non_neg_integer() | nil
        }

  defstruct include_metadata: true,
            include_embedded: true,
            max_content_chars: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
