# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:710f05a00d2a8480674a89aedd19b116f8dbb0ed7f783a861cc206a879e7e001
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil,
            attributes: nil
end
