# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b8c0aacd9361296cae3ffbdd8b03f1500611f441295fd45286b8589d7afced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do  @moduledoc "Image element in Djot."
  defstruct src: "",
            alt: "",
            title: nil,
            attributes: nil
end
