# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a827892719dd644d081f7fb58726508748c012b3709fd5c7f1bc2208046eba9f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do  @moduledoc "A single node in the document tree."
  defstruct id: "",
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
