# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          strategy: String.t() | nil,
          token_count: non_neg_integer() | nil
        }

  defstruct text: nil,
            strategy: :extractive,
            token_count: nil
end
