# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48e53c254df716fd61e9b6c82f671eb0267667bddf8cc26d8ab9c8df8b1b035c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do  @moduledoc "A resolved relationship between two nodes in the document tree."
  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
