# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3825ea5baf0d05de69971acc2a024db8a93b4ac6dc39861c717da7d5d34246a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc """
  Top-level structured document representation.

  A flat array of nodes with index-based parent/child references forming a tree.
  Root-level nodes have `parent: None`. Use `body_roots()` and `furniture_roots()`
  to iterate over top-level content by layer.

  # Validation

  Call `validate()` after construction to verify all node indices are in bounds
  and parent-child relationships are bidirectionally consistent.
  """

  @typedoc "Top-level structured document representation."
  @type t :: %__MODULE__{
          nodes: [map()],
          source_format: String.t() | nil,
          relationships: [map()],
          node_types: [String.t()]
        }

  defstruct nodes: [],
            source_format: nil,
            relationships: [],
            node_types: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
