# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb87feb67a874d4254fec6cd406c755ca5ab34b683f26fe41f4b275f6309dd87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Drawing do  @moduledoc "A drawing object extracted from `<w:drawing>`."
  defstruct drawing_type: "",
            extent: "",
            doc_properties: "",
            image_ref: ""
end
