# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4fb201933996c240b4647670f46ad0e77472697d29626e89468bd31fab11b95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_id: String.t() | nil,
          element_type: String.t() | nil,
          text: String.t() | nil,
          metadata: map()
        }

  defstruct element_id: nil,
            element_type: :title,
            text: nil,
            metadata: nil
end
