# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f4cb1aff2c28906f7681305c320e0d8ba06487752adcb853cfb6789a68bf7408
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do  @moduledoc "Semantic element extracted from document."
  defstruct element_id: "",
            element_type: :title,
            text: "",
            metadata: nil
end
