# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a3c9515252cb2667970473e1656984d163e05e7919e658182a474292055c84cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          diff: map()
        }

  defstruct path: nil,
            diff: nil
end
