# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          diff: map()
        }

  defstruct path: nil,
            diff: nil
end
