# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c21040f44dd2eefb07a72ebfdc7d88f9a51d13be6af8e7c879a250ba7146333
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do  @moduledoc "Request parameters for embedding generation."
  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
