# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:17c75e80aa1ae9ccc702a5b3779e2ce3ee42d1cce3a91c403c973c82749d19de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            mime_type: nil
end
