# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
          added: [map()],
          removed: [map()],
          changed: [map()]
        }

  defstruct added: [],
            removed: [],
            changed: []
end
