# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b78366e4fb008e88d67acb0610b63ca8e798dd7c79bbcbf852e62203aa29c546
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do  @moduledoc "Excel workbook representation."
  defstruct sheets: [],
            metadata: %{}
end
