# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map(),
          revisions: [map()] | nil
        }

  defstruct sheets: [],
            metadata: %{},
            revisions: nil
end
