# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @spec native() :: t()
  def native, do: @native
  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec mixed() :: t()
  def mixed, do: @mixed
end
