# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractionResult` values."

  @typedoc "The complete diff between two `ExtractionResult` values."
  @type t :: %__MODULE__{
          content_diff: [map()],
          tables_added: [map()],
          tables_removed: [map()],
          tables_changed: [map()],
          metadata_changed: String.t() | nil,
          embedded_changes: map()
        }

  defstruct content_diff: [],
            tables_added: [],
            tables_removed: [],
            tables_changed: [],
            metadata_changed: nil,
            embedded_changes: nil
end
