# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b389e52cf95f9bbb03885b07393f20a34441f1d44eae4855f492e527973f144
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedInlineImage do  @moduledoc "Extracted inline image with metadata."
  defstruct data: "",
            format: "",
            filename: nil,
            description: nil,
            dimensions: nil,
            attributes: []
end
