# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c6f0f7a085f10fe7e1da4ec542773192dd658dc67e638494e54124a7f1ca9295
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do  @moduledoc "FictionBook (FB2) metadata."
  defstruct genres: [],
            sequences: [],
            annotation: ""
end
