# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:13edc7c7702a64bfe18b88fdab97d78ac5f838d22fd8c9e4602defe3fa7828c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FileExtractionConfig do  @moduledoc "Per-file extraction configuration overrides for batch processing."
  defstruct enable_quality_processing: false,
            ocr: nil,
            force_ocr: false,
            force_ocr_pages: [],
            disable_ocr: false,
            chunking: nil,
            content_filter: nil,
            images: nil,
            pdf_options: nil,
            token_reduction: nil,
            language_detection: nil,
            pages: nil,
            keywords: nil,
            postprocessor: nil,
            html_options: "",
            result_format: :unified,
            output_format: :plain,
            include_document_structure: false,
            layout: nil,
            timeout_secs: 0,
            tree_sitter: nil,
            structured_extraction: nil
end
