# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bbaa5e61006084187ac137ea50650239a4625b0c12c23a60d68941232504e678
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do  @moduledoc "Block-level element in a Djot document."
  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
