# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa483ba522738b612f6a6524446be9b4848a626f114fb8b5b14d2087e0512603
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do  @moduledoc "Heading context for a chunk within a Markdown document."
  defstruct headings: []
end
