# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f71dec843c6e637d3ee0e309ac8a730b6e4d91adbbe3bc807e68b0ab82b7a66
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."
  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
