# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ImagePreprocessingMetadata do
  @moduledoc """
  Image preprocessing metadata.

  Tracks the transformations applied to an image during OCR preprocessing,
  including DPI normalization, resizing, and resampling.
  """

  @typedoc "Image preprocessing metadata."
  @type t :: %__MODULE__{
          target_dpi: integer(),
          scale_factor: float(),
          auto_adjusted: boolean(),
          final_dpi: integer(),
          resample_method: String.t() | nil,
          dimension_clamped: boolean(),
          calculated_dpi: integer() | nil,
          skipped_resize: boolean(),
          resize_error: String.t() | nil
        }

  defstruct target_dpi: 0,
            scale_factor: 0.0,
            auto_adjusted: false,
            final_dpi: 0,
            resample_method: nil,
            dimension_clamped: false,
            calculated_dpi: nil,
            skipped_resize: false,
            resize_error: nil
end
