# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          image_type: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            image_type: :data_uri
end
