# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:709a767f064ad4dbcfc0bf6261bd5202dfd03e07f8a0c7c8a5cfa49ff99fe239
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InfoResponse do  @moduledoc "Server information response."
  defstruct version: "",
            rust_backend: false
end
