# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          score: float(),
          algorithm: String.t() | nil,
          positions: [non_neg_integer()] | nil
        }

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
