# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: String.t() | nil,
          confidence: float(),
          bbox: map()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
