# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: []
end
