# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0bea35e33e059112afeebb2ac18fbf6ece6bf01de8abc40c3370b3ca8724cd99
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()],
          attributes: [String.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
