# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LlmBackend do
  @moduledoc "liter-llm-backed NER backend."

  alias Kreuzberg.Native
  defstruct [:ref]

  @typedoc "liter-llm-backed NER backend."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Create a new LLM-backed NER backend with the given LLM configuration."
  def new(config) do
    ref = Native.llmbackend_new(config)
    %__MODULE__{ref: ref}
  end

  def detect(obj, text, categories) do
    Native.llmbackend_detect_async(obj.ref, text, categories)
  end

  def detect_with_custom(obj, text, categories, custom_labels) do
    Native.llmbackend_detect_with_custom_async(obj.ref, text, categories, custom_labels)
  end
end
