# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LlmBackend do
  @moduledoc "liter-llm-backed NER backend."

  alias Kreuzberg.Native
  defstruct [:ref]

  @typedoc "liter-llm-backed NER backend."
  @type t :: %__MODULE__{ref: reference()}

  def new(config) do
    ref = Native.llmbackend_new(config)
    %__MODULE__{ref: ref}
  end

  def detect(obj, text, categories) do
    Native.llmbackend_detect_async(obj.ref, text, categories)
  end

  def detect_with_custom(obj, text, categories, custom_labels) do
    Native.llmbackend_detect_with_custom_async(obj.ref, text, categories, custom_labels)
  end
end
