# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:97ff556105fb4ba5e119208196c2f5c4724830d59550060fe85da298db31de55
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do  @moduledoc "Configuration for OCR element extraction."
  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
