# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cef9590967ec934ff8b6dbf06d6b471f2a1e7ae93c30269ed01c185c56bb08f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do  @moduledoc "OCR processing metadata."
  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
