# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrConfidence do
  @moduledoc """
  Confidence scores for an OCR element.

  Separates detection confidence (how confident that text exists at this location)
  from recognition confidence (how confident about the actual text content).
  """

  @typedoc "Confidence scores for an OCR element."
  @type t :: %__MODULE__{
          detection: float() | nil,
          recognition: float()
        }

  defstruct detection: nil,
            recognition: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
