# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3637e901517e2ae3ad2be4278a6b07a8a93e56f8940b5aa919f40203ed1831e3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."
  defstruct stages: [],
            quality_thresholds: nil
end
