# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          labels: [map()]
        }

  defstruct page_number: 0,
            labels: []
end
