# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba836f229f3d9e0d15c407a3cce825b96630e094d648edd5281114085c40906d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageHierarchy do  @moduledoc "Page hierarchy structure containing heading levels and block information."
  defstruct block_count: 0,
            blocks: []
end
