# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:00a8062bcc4c349551ee940b90877f0288242157b6afbc89e94ab7fe74666477
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do  @moduledoc "Content for a single page/slide."
  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
