# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2b53b294b11cedbb00b4445b50165ff03faac90a3592b0f93781dce7aa90bf43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfConfig do  @moduledoc "PDF-specific configuration."
  defstruct extract_images: false,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false
end
