# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
          annotation_type: String.t() | nil,
          content: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: map() | nil
        }

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
