# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4a1c465e4c4f046474b3b7f0f6dd840827d1735238b59081f326f438a79b671
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfAnnotation do  @moduledoc "A PDF annotation extracted from a document page."
  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
