# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:034586f99da681b408e66f0c3ac403a62c0c13bc0531299cef1cf49152c322f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PoolError do  @moduledoc "Error type for pool operations."
  @type t :: :lock_poisoned

  @lock_poisoned :lock_poisoned

  @spec lock_poisoned() :: t()
  def lock_poisoned, do: @lock_poisoned
end
