# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1966e033cc877aa333ee84ba1ea1e47934b15620937eee050f84a31e81e9e46
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do  @moduledoc "PowerPoint presentation metadata."
  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
