# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b19bbad7a69f7d1613356c6d049e6d5f8dd076796f03a0ebc15e46f3dab2ab83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do  @moduledoc "Processing stages for post-processors."
  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @spec early() :: t()
  def early, do: @early
  @spec middle() :: t()
  def middle, do: @middle
  @spec late() :: t()
  def late, do: @late
end
