# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct x: 0,
            y: 0,
            width: 0,
            height: 0
end
