# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  @typedoc "RAKE-specific parameters."
  @type t :: %__MODULE__{
          min_word_length: non_neg_integer(),
          max_words_per_phrase: non_neg_integer()
        }

  defstruct min_word_length: 1,
            max_words_per_phrase: 3

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
