# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0fac685069bf891517ea3d2b4943b1e2dba424e963ebf1cc5b0170b0fd083dc3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do  @moduledoc "RAKE-specific parameters."
  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
