# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionPattern do
  @moduledoc """
  One user-supplied regex pattern to redact.

  The pattern is compiled with the Rust `regex` crate (no look-around). Case
  sensitivity is encoded in the pattern via the `(?i)` inline flag when
  [`Self::case_sensitive`] is `false`.
  """

  @typedoc "One user-supplied regex pattern to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          pattern: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            pattern: nil,
            case_sensitive: false
end
