# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a3c9515252cb2667970473e1656984d163e05e7919e658182a474292055c84cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionConfig do
  @moduledoc "Configuration for the redaction post-processor."

  @typedoc "Configuration for the redaction post-processor."
  @type t :: %__MODULE__{
          categories: [String.t() | nil],
          strategy: String.t() | nil,
          ner: map() | nil,
          preserve_offsets: boolean(),
          custom_terms: [map()],
          custom_patterns: [map()]
        }

  defstruct categories: [],
            strategy: :mask,
            ner: nil,
            preserve_offsets: true,
            custom_terms: [],
            custom_patterns: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
