# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fb96bc423130c5157db1f6d0336ff8a4a8ec9772bbbc7fa41d6c76984b16637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RevisionKind do
  @moduledoc "Semantic classification of a tracked change."

  @typedoc "Semantic classification of a tracked change."
  @type t :: :insertion | :deletion | :format_change | :comment

  @insertion :insertion
  @deletion :deletion
  @format_change :format_change
  @comment :comment

  @doc "Text or content was inserted."
  @spec insertion() :: t()
  def insertion, do: @insertion
  @doc "Text or content was deleted."
  @spec deletion() :: t()
  def deletion, do: @deletion
  @doc "Run-level formatting (font, size, colour, …) was changed."
  @spec format_change() :: t()
  def format_change, do: @format_change
  @doc "A reviewer comment or annotation."
  @spec comment() :: t()
  def comment, do: @comment
end
