# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Segment do
  @moduledoc "A text segment with its byte offset in the original document."

  @typedoc "A text segment with its byte offset in the original document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          byte_start: non_neg_integer()
        }

  defstruct text: nil,
            byte_start: 0
end
