# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c4144f3b08738bf1517fd1a22d67ff94122d904be0c54ad265870642df4c6ee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do  @moduledoc "API server configuration."
  defstruct host: "",
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
