# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4510797f96cb033f008011669d807a17fa9d7f26dbeefd1553130fc5bf31276e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionResponse do  @moduledoc "Response from structured extraction endpoint."
  defstruct structured_output: "",
            content: "",
            mime_type: ""
end
