# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.SummaryStrategy do
  @moduledoc "Summarisation strategy."

  @typedoc "Summarisation strategy."
  @type t :: :extractive | :abstractive

  @extractive :extractive
  @abstractive :abstractive

  @doc "Pure-Rust extractive summary (TextRank over the chunk graph). Deterministic, fast, no external service required."
  @spec extractive() :: t()
  def extractive, do: @extractive
  @doc "Abstractive summary produced by liter-llm. Requires `liter-llm` feature and a configured `LlmConfig`. Token usage is captured in [`ExtractionResult::llm_usage`](super::extraction::ExtractionResult::llm_usage)."
  @spec abstractive() :: t()
  def abstractive, do: @abstractive
end
