# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:84898a78498e012706f0134c7feb694a360b8dd0e17f3a49dffd37c169d0e3a6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do  @moduledoc "A supported document format entry."
  defstruct extension: "",
            mime_type: ""
end
