# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a3c9515252cb2667970473e1656984d163e05e7919e658182a474292055c84cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Kreuzberg.Native

  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_default()}
  end

  def default() do
    ref = Native.tokencounter_default()
    %__MODULE__{ref: ref}
  end
end
