# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a18ad6cc5d991698cf1b1346faf582f251b6f418b9b4127ee3356b648e2c7878
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterConfig do  @moduledoc "Configuration for tree-sitter language pack integration."
  defstruct enabled: true,
            cache_dir: nil,
            languages: nil,
            groups: nil,
            process: nil
end
