# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7df1aea06133d24ffd189ee1719234f769dae1b2a1c1f448285b950169eb02a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YakeParams do  @moduledoc "YAKE-specific parameters."
  defstruct window_size: 2
end
