# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
