# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ad547b1b7ad0e4c516930ccf0749bebef29ee2be7cf531be6d41950dbceee275
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
