// DO NOT EDIT - auto-generated by alef
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new BadMetaSchemaException with the given message. */
    public BadMetaSchemaException(final String message) {
        super(message);
    }

    /** Creates a new BadMetaSchemaException with the given message and cause. */
    public BadMetaSchemaException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
