// DO NOT EDIT - auto-generated by alef
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new BadMetaSchemaException with the given message. */
    public BadMetaSchemaException(final String message) {
        super(message);
    }

    /** Creates a new BadMetaSchemaException with the given message and cause. */
    public BadMetaSchemaException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
