// DO NOT EDIT - auto-generated by alef
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DeserializeException with the given message. */
    public DeserializeException(final String message) {
        super(message);
    }

    /** Creates a new DeserializeException with the given message and cause. */
    public DeserializeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
