// DO NOT EDIT - auto-generated by alef
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
package io.xberg;

/**
 * The embedding model or embedding pipeline returned an error.
 */
public class EmbeddingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
