// DO NOT EDIT - auto-generated by alef
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new HeuristicsErrorException with the given message. */
    public HeuristicsErrorException(final String message) {
        super(message);
    }

    /** Creates a new HeuristicsErrorException with the given message and cause. */
    public HeuristicsErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
