// DO NOT EDIT - auto-generated by alef
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new HeuristicsErrorException with the given message. */
    public HeuristicsErrorException(final String message) {
        super(message);
    }

    /** Creates a new HeuristicsErrorException with the given message and cause. */
    public HeuristicsErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
