// DO NOT EDIT - auto-generated by alef
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
package io.xberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new IdMismatchException with the given message. */
    public IdMismatchException(final String message) {
        super(message);
    }

    /** Creates a new IdMismatchException with the given message and cause. */
    public IdMismatchException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
