// DO NOT EDIT - auto-generated by alef
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
package io.xberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdMismatchException with the given message. */
  public IdMismatchException(final String message) {
    super(message);
  }

  /** Creates a new IdMismatchException with the given message and cause. */
  public IdMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
