// DO NOT EDIT - auto-generated by alef
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
package io.xberg;

/**
 * An internal `Mutex` or `RwLock` was found in a poisoned state.
 */
public class LockPoisonedException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
