// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * NER backend selector.
 */
@SuppressWarnings("PMD")
public enum NerBackendKind {
    /**
     * {@code xberg-gliner} ONNX inference. Requires {@code ner-onnx} feature. Models
     * download lazily from {@code xberg-io/gliner-models}.
     */
    Onnx("onnx"),
    /**
     * liter-llm zero-shot NER via structured-output prompts. Requires {@code ner-llm}
     * feature. Useful when domain-specific categories outstrip the ONNX taxonomy.
     */
    Llm("llm");


    /** The string value. */
    private final String value;

    NerBackendKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static NerBackendKind fromValue(final String value) {
        for (NerBackendKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown NerBackendKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
