// DO NOT EDIT - auto-generated by alef
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
package io.xberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
