// DO NOT EDIT - auto-generated by alef
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParseException with the given message. */
    public ParseException(final String message) {
        super(message);
    }

    /** Creates a new ParseException with the given message and cause. */
    public ParseException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
