// DO NOT EDIT - auto-generated by alef
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
package io.xberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
