// DO NOT EDIT - auto-generated by alef
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new PdfAnalysisErrorException with the given message. */
    public PdfAnalysisErrorException(final String message) {
        super(message);
    }

    /** Creates a new PdfAnalysisErrorException with the given message and cause. */
    public PdfAnalysisErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
