// DO NOT EDIT - auto-generated by alef
// alef:hash:5c17df01a07b64aec1679fefd838270e2db79779ee5c6c7c2659e29f3068e938
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new PdfAnalysisErrorException with the given message. */
    public PdfAnalysisErrorException(final String message) {
        super(message);
    }

    /** Creates a new PdfAnalysisErrorException with the given message and cause. */
    public PdfAnalysisErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
