// DO NOT EDIT - auto-generated by alef
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
package io.xberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) {
    super(message);
  }

  /** Creates a new SchemaNotObjectException with the given message and cause. */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
