// DO NOT EDIT - auto-generated by alef
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
package io.xberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
