// DO NOT EDIT - auto-generated by alef
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
