// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * URL extraction mode.
 */
@SuppressWarnings("PMD")
public enum UrlExtractionMode {
    /**
     * Classify HTTP(S) resources after fetch.
     */
    Auto("auto"),
    /**
     * Treat the URI as a single remote document/page.
     */
    Document("document"),
    /**
     * Crawl from the seed URI and extract discovered pages/documents.
     */
    Crawl("crawl");


    /** The string value. */
    private final String value;

    UrlExtractionMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static UrlExtractionMode fromValue(final String value) {
        for (UrlExtractionMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown UrlExtractionMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
