// DO NOT EDIT - auto-generated by alef
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
