// DO NOT EDIT - auto-generated by alef
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
