// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:072799a06d0d5e56086d61564f21b0e16250fe439a5f0664a2a6c3e06fe93a73
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  clearPostProcessors,
  listPostProcessors,
  WasmImagePreprocessingConfig,
  WasmTreeSitterProcessConfig,
  WasmLlmConfig,
  WasmOcrElementConfig,
  WasmStructuredExtractionConfig,
  WasmLanguageDetectionConfig,
  WasmImageExtractionConfig,
  WasmHierarchyConfig,
  WasmEmbeddingConfig,
  WasmOcrConfig,
  WasmPostProcessorConfig,
  WasmRakeParams,
  WasmTokenReductionOptions,
  WasmLayoutDetectionConfig,
  WasmAccelerationConfig,
  WasmOcrPipelineConfig,
  WasmHtmlOutputConfig,
  WasmOcrPipelineStage,
  WasmYakeParams,
  WasmTesseractConfig,
  WasmContentFilterConfig,
  WasmEmailConfig,
  WasmPageConfig,
  WasmSecurityLimits,
  WasmKeywordConfig,
  WasmOcrQualityThresholds,
  WasmPdfConfig,
  WasmChunkingConfig,
  WasmTreeSitterConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("post_processor_management", () => {
  it("post_processors_clear: Clear all post-processors and verify list is empty", () => {
    clearPostProcessors();
  });
  it("post_processors_list: List all registered post-processors", () => {
    listPostProcessors();
  });
});
