// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:daa5b018d74636f0a531f204da732f80c82334f623079eda33a424144ad49da5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  getExtensionsForMime,
  WasmTreeSitterConfig,
  WasmTreeSitterProcessConfig,
  WasmLlmConfig,
  WasmStructuredExtractionConfig,
  WasmOcrElementConfig,
  WasmLanguageDetectionConfig,
  WasmImageExtractionConfig,
  WasmHierarchyConfig,
  WasmEmbeddingConfig,
  WasmOcrConfig,
  WasmLayoutDetectionConfig,
  WasmTokenReductionOptions,
  WasmRakeParams,
  WasmPostProcessorConfig,
  WasmAccelerationConfig,
  WasmOcrPipelineConfig,
  WasmHtmlOutputConfig,
  WasmOcrPipelineStage,
  WasmYakeParams,
  WasmContentFilterConfig,
  WasmTesseractConfig,
  WasmEmailConfig,
  WasmPageConfig,
  WasmSecurityLimits,
  WasmOcrQualityThresholds,
  WasmChunkingConfig,
  WasmPdfConfig,
  WasmKeywordConfig,
  WasmImagePreprocessingConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("registry_operations", () => {
  it("extensions_docx: Get file extensions for DOCX MIME type", () => {
    getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  });
  it("extensions_html: Get file extensions for HTML MIME type", () => {
    getExtensionsForMime("text/html");
  });
  it("extensions_pdf: Get file extensions for PDF MIME type", () => {
    const result = getExtensionsForMime("application/pdf");
    expect(result).toContain("pdf");
  });
});
