// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f276bdb4877bf05f504b71ebbe01e2caf9e7fc3bc3ab85431d388678c2ae7b7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  extractBytes,
  WasmExtractionConfig,
  WasmImagePreprocessingConfig,
  WasmTreeSitterProcessConfig,
  WasmLlmConfig,
  WasmOcrElementConfig,
  WasmStructuredExtractionConfig,
  WasmLanguageDetectionConfig,
  WasmImageExtractionConfig,
  WasmHierarchyConfig,
  WasmEmbeddingConfig,
  WasmOcrConfig,
  WasmPostProcessorConfig,
  WasmTokenReductionOptions,
  WasmLayoutDetectionConfig,
  WasmRakeParams,
  WasmAccelerationConfig,
  WasmOcrPipelineConfig,
  WasmHtmlOutputConfig,
  WasmOcrPipelineStage,
  WasmYakeParams,
  WasmContentFilterConfig,
  WasmTesseractConfig,
  WasmEmailConfig,
  WasmPageConfig,
  WasmSecurityLimits,
  WasmPdfConfig,
  WasmChunkingConfig,
  WasmKeywordConfig,
  WasmOcrQualityThresholds,
  WasmTreeSitterConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("smoke", () => {
  it("ocr_image_png: OCR: PNG image extraction with OCR enabled. In WASM this exercises the Uint8Array bridge parameter and Promise await in the generated OcrBackend bridge.", async () => {
    const _content_content = await (
      await import("node:fs/promises")
    ).readFile("images/test_hello_world.png");
    const result = await extractBytes(_content_content, "image/png", undefined);
    expect(result.mimeType.trim()).toBe("image/png");
    expect(result.content.length).toBeGreaterThanOrEqual(1);
    expect(["Hello", "World", "hello", "world"].some((v) => result.content.includes(v))).toBe(true);
  });
});
