# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'async' do
  it 'async_extract_bytes: Async extract_bytes call on PDF document' do
    content = File.read("pdf/fake_memo.pdf").bytes
    result = Kreuzberg.extract_bytes_async(content, 'application/pdf')
    expect(result.mime_type.to_s.strip).to eq('application/pdf'.strip)
    expect(result.content.length).to be >= 50

  end

  it 'async_extract_bytes_empty_mime: extract_bytes empty MIME async' do
    expect {
      content = File.read("text/plain.txt").bytes
      Kreuzberg.extract_bytes_async(content, '', Kreuzberg::ExtractionConfig.new())
    }.to raise_error(RuntimeError)
  end

  it 'async_extract_bytes_invalid_mime: extract_bytes unsupported MIME async' do
    expect {
      content = File.read("text/plain.txt").bytes
      Kreuzberg.extract_bytes_async(content, 'application/x-nonexistent', Kreuzberg::ExtractionConfig.new())
    }.to raise_error(RuntimeError)
  end
end
