# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bddb26c184c7bc6daf378e805aa5846776211701b96ff693f11a8e712c8dabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'code' do
  it 'code_shebang_detection: Test language detection from shebang line via bytes input' do
    result = Kreuzberg.extract_file_sync('code/script.sh', 'text/x-source-code')
    expect(result.mime_type.to_s.strip).to eq('text/x-source-code'.strip)
    expect(result.content.length).to be >= 10
    expect(result.content.to_s).to include('build')
    expect(result.content.to_s).to include('clean')

  end
end
