# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba2bf524a11e4984b43c63b159f9691f23935a4c73f5ff11fc2d0cd506ce0dd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'embed_extra' do
  it 'embed_texts_batch: Batch embed texts' do
    result = Kreuzberg.embed_texts(['Hello', 'World'], {model: { 'name' => 'balanced', 'type' => 'preset' }})

    expect(result).not_to be_nil
  end
end
