# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:02787f99435c8d4c1989027a5ed350a5b8f5f4c36b346dd34b9530b917155191
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'embed_extra' do
  it 'embed_texts_batch: Batch embed texts' do
    result = Kreuzberg.embed_texts(['Hello', 'World'], {})

    expect(result).not_to be_nil
  end
end
