# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require "spec_helper"
require "xberg"
require "json"

RSpec.describe "post_processor_management" do
  it "post_processors_clear: Clear all post-processors and verify list is empty" do
    Xberg.clear_post_processors
  end

  it "post_processors_list: List all registered post-processors" do
    result = Xberg.list_post_processors

    expect(result).not_to(be_nil)
  end
end
