# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89d726108580a0cadfba8e5fed04b649367d34676c9f3a67fc74e470e76852de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'renderer_management' do
  it 'renderers_clear: Clear all renderers and verify list is empty' do
    Kreuzberg.clear_renderers()

  end

  it 'renderers_list: List all registered renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end
end
