# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da0971ffb87a5da8280d9c21dee6dcc820cc60b0a7fa9fc0d801e39894723f87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'reranker_backend_management' do
  it 'clear_reranker_backends: Clear all reranker backends and verify list is empty' do
    Kreuzberg.clear_reranker_backends()

  end

  it 'list_reranker_backends: List all registered reranker backends' do
    result = Kreuzberg.list_reranker_backends()

    expect(result).not_to be_nil
  end
end
