# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'rerank_async_pending' do
  it 'async_rerank: rerank_async: plugin model with no backend registered returns an error' do
    expect {
      Xberg.rerank_async('neural networks', ['Neural networks are a class of machine learning models inspired by biological brains.', 'The Eiffel Tower is located in Paris.', 'Convolutional neural networks excel at image recognition tasks.'], {model: { 'name' => 'async_rerank', 'type' => 'plugin' }})
    }.to raise_error(RuntimeError)
  end
end
