# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    Kreuzberg.clear_validators()

  end

  it 'validators_list: List all registered validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
