<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef91a8e781d68f16c257c176155b0867c2ad54216d6eb280e304f266aa03aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../packages/php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
// Change to the configured test-documents directory so that fixture file
// paths like "pdf/fake_memo.pdf" resolve correctly when running phpunit
// from e2e/php/.
$_test_documents = __DIR__ . '/../../test_documents';
if (is_dir($_test_documents)) {
    chdir($_test_documents);
}
