// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embed_extra
package e2e_test

import (
	"encoding/json"
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_EmbedTextsBatch(t *testing.T) {
	// Batch embed texts
	var texts []string
	if err := json.Unmarshal([]byte(`["hello","world"]`), &texts); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	var config xberg.EmbeddingConfig
	if err := json.Unmarshal([]byte(`{"model":{"name":"balanced","type":"preset"}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := xberg.EmbedTextsAsync(texts, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
