// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: registry
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_ListEmbeddingBackends(t *testing.T) {
	// List embedding backends
	_, err := xberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListOcrBackends(t *testing.T) {
	// List OCR backends
	_, err := xberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListPostProcessors(t *testing.T) {
	// List post-processors
	_, err := xberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListRenderers(t *testing.T) {
	// List renderers
	_, err := xberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListValidators(t *testing.T) {
	// List validators
	_, err := xberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
