// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:186120190dc3fa85092d48c82ebd6b0cc6ee2de2c96043045d9507c1ba55ba26
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	_ = xberg.ClearRenderers()
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := xberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
