// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b6c645c306374dfeead41c0dbe41cfc982d6148610105592b11c156676166394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: reranker_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_ClearRerankerBackends(t *testing.T) {
	// Clear all reranker backends and verify list is empty
	_ = xberg.ClearRerankerBackends()
}

func Test_ListRerankerBackends(t *testing.T) {
	// List all registered reranker backends
	_, err := xberg.ListRerankerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
