// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f14c9481ad7ed053acf7aacbe118e0ec5ffe8d33a86436383442e749d18579db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: reranker_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_ClearRerankerBackends(t *testing.T) {
	// Clear all reranker backends and verify list is empty
	_ = xberg.ClearRerankerBackends()
}

func Test_ListRerankerBackends(t *testing.T) {
	// List all registered reranker backends
	_, err := xberg.ListRerankerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
