// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc58d2f26634769e6a959f3287d476b61b9298dadaafd3aeb2689ba60acc4c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: detection. */
class DetectionTest {
    @Test
    fun testDetectMimeBytesHtml() = runBlocking {
        // Detect HTML MIME from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes("html/html.html")
    }

    @Test
    fun testDetectMimeBytesPdf() = runBlocking {
        // Detect PDF MIME type from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes("pdf/fake_memo.pdf")
    }

    @Test
    fun testDetectMimeBytesPng() = runBlocking {
        // Detect PNG MIME type from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes("images/test_hello_world.png")
    }

    @Test
    fun testGetExtensionsUnknownMime() = runBlocking {
        // get_extensions unknown MIME
        assertFailsWith<Exception> {
            Kreuzberg.getExtensionsForMime("application/x-totally-unknown")
        }
        Unit
    }

}
