// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import dev.kreuzberg.DocumentExtractorBridge

/** E2e tests for category: document_extractor_management. */
class DocumentExtractorManagementTest {
    @Test
    fun testDocumentExtractorsClear() = runBlocking {
        // Clear all document extractors and verify list is empty
        val result = DocumentExtractorBridge.clearAll()
    }

    @Test
    fun testExtractorsList() = runBlocking {
        // List all registered document extractors
        val result = Kreuzberg.listDocumentExtractors()
    }

}
