// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: pdf. */
class PdfTest {
    @Test
    fun testRenderPdfPageFirst() = runBlocking {
        // render_pdf_page_to_png: first page
        val result = Kreuzberg.renderPdfPageToPng(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/fake_memo.pdf")), 0)
        assertTrue(result.size >= 100, "expected size >= 100")
    }

    @Test
    fun testRenderPdfPageOutOfRange() = runBlocking {
        // render_pdf_page_to_png: page out of range
        assertFailsWith<Exception> {
            Kreuzberg.renderPdfPageToPng(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/fake_memo.pdf")), 999)
        }
        Unit
    }

}
