// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a0fead48e5425cbebed4605ab3891eada2f5502877db31e2a734de7b0293ff95
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: registry. */
class RegistryTest {
    @Test
    fun testListDocumentExtractors() = runBlocking {
        // List document extractors
        val result = Kreuzberg.listDocumentExtractors()
    }

    @Test
    fun testListEmbeddingBackends() = runBlocking {
        // List embedding backends
        val result = Kreuzberg.listEmbeddingBackends()
    }

    @Test
    fun testListOcrBackends() = runBlocking {
        // List OCR backends
        val result = Kreuzberg.listOcrBackends()
    }

    @Test
    fun testListPostProcessors() = runBlocking {
        // List post-processors
        val result = Kreuzberg.listPostProcessors()
    }

    @Test
    fun testListRenderers() = runBlocking {
        // List renderers
        val result = Kreuzberg.listRenderers()
    }

    @Test
    fun testListValidators() = runBlocking {
        // List validators
        val result = Kreuzberg.listValidators()
    }

}
