// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff70b1068502668e3ef204b91b23a71756405616bb438f660a22efce5ecfa607
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import dev.kreuzberg.ValidatorBridge

/** E2e tests for category: validator_management. */
class ValidatorManagementTest {
    @Test
    fun testValidatorsClear() = runBlocking {
        // Clear all validators and verify list is empty
        val result = ValidatorBridge.clearAll()
    }

    @Test
    fun testValidatorsList() = runBlocking {
        // List all registered validators
        val result = Kreuzberg.listValidators()
    }

}
