// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba2bf524a11e4984b43c63b159f9691f23935a4c73f5ff11fc2d0cd506ce0dd4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: validator_management. */
class ValidatorManagementTest {
    @Test
    fun testValidatorsClear() = runBlocking {
        // Clear all validators and verify list is empty
        val result = ValidatorBridge.clearAll()
    }

    @Test
    fun testValidatorsList() = runBlocking {
        // List all registered validators
        val result = Kreuzberg.listValidators()
    }

}
